[package]
name = "sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixcil = { path = "../", version = "0.2" }
pagurus = { version = "0.3" }
pagurus_sdl_system = { version = "0.3" }
